# Generated by Django 3.2 on 2021-05-08 18:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('doc_link', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('lang', models.CharField(max_length=8)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('publisher', models.CharField(max_length=256)),
                ('published', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('searchQuery', models.CharField(max_length=512)),
                ('title', models.CharField(default=None, max_length=256)),
                ('description', models.CharField(default=None, max_length=4096)),
                ('lang', models.CharField(default=None, max_length=8)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=128), size=None)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=128), size=None)),
                ('publisher', models.CharField(default=None, max_length=256)),
                ('published_before', models.IntegerField()),
                ('published_after', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueriesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.document')),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.searchquery')),
            ],
            options={
                'unique_together': {('query_id', 'document_id')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.document')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'document_id')},
            },
        ),
    ]
